apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jira
  namespace: atlassian
  annotations:
    volume.beta.kubernetes.io/storage-class: example-sc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1000Mi
